<?=$this->form;?>
<table>
    
    <?php foreach( $this->report->ReportJoin as $join ): ?>
    <tr>
        <td><?=$join->model?></td>
        <td><a href="<?=$this->url(array(
            'action' => 'remove-join',
            'joinModel' => $join->id
        ));?>">Remover</a></td>
    </tr>
    <?php endforeach;?>
</table>

<button dojoType="dijit.form.Button" label="Avançar">
    <script type='dojo/method' event='onClick'>
        dojo.doc.location.pathname = '/report/column';
    </script>
</button>