<?php

/**
 * Schedule
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Schedule extends BaseSchedule
{

    /**
     * @var string
     */
    static protected $_tableName = "Schedule";

    /**
     * Return a cron like string (* * * * * *)
     * @return string 
     */
    public function getPeriod()
    {
        $period = "{$this->minute} "
                . "{$this->hour} "
                . "{$this->day} "
                . "{$this->month} "
                . "{$this->year} "
                . "{$this->weekday} ";
                
      return $period;
    }

    /**
     * Return a schedule
     * @param integer $id
     * @return Schedule
     */
    static function find($id)
    {
        //@TODO limitate to own schedules
        $schedule = Doctrine_Query::create()
                        ->from(self::$_tableName)
                        ->where('id = ?', array($id))
                        ->execute();

        return $schedule;
    }


}